### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by ibrahimseleem** [HyodaKazuaki/Parallax-FeedBack-360-Servo-Control-Library-4-Arduino#2]
The code doesn't compatible with Arduino Due

**Comment by HyodaKazuaki** [comment]
Very nice.
I think it have no problem on "library.properties" with your suggested changes, but I found that some code needs to be changed.
I'll update code and release beta, so could you check beta library which works?

**Comment by ibrahimseleem** [comment]
Yes, I tried it right now. It is now compatible with Arduino DUE. But, there are errors due to definitions in .h and .cpp files.

I will work on it.

**Comment by ibrahimseleem** [comment]
I will try and submit a feedback

**Comment by ibrahimseleem** [comment]
After modification to .h and .cpp files, the library already worked with Arduino DUE. I uploaded this video to verify this result, you can see here [https://www.youtube.com/watch?v=PhXOE_CzhMo](url)

Here is the library with modifications. Thanks a lot.
[Parallax-FeedBack-360-Servo-Control-Library-4-Arduino.zip](https://github.com/HyodaKazuaki/Parallax-FeedBack-360-Servo-Control-Library-4-Arduino/files/10273946/Parallax-FeedBack-360-Servo-Control-Library-4-Arduino.zip)
